
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package backend.analizadorParaRespuestaServidor;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAYOR_QUE = 5;
  public static final int MENOR_QUE = 4;
  public static final int DIAGONAL = 3;
  public static final int error = 1;
  public static final int ORACION = 6;
  public static final int EOF = 0;
  public static final int MENSAJE = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MENSAJE",
  "DIAGONAL",
  "MENOR_QUE",
  "MAYOR_QUE",
  "ORACION"
  };
}

