
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package backend.analizadorParaTextoDeCliente;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IDENTIFICADOR_COMILLA = 55;
  public static final int DIAGONAL = 12;
  public static final int NUMERO = 49;
  public static final int ALINEACION = 40;
  public static final int BORRAR_PAGINA = 28;
  public static final int PAGINA = 31;
  public static final int PARAMETROS = 4;
  public static final int NOMBRE = 8;
  public static final int FORMATO_FECHA = 50;
  public static final int ANCHO = 48;
  public static final int ORACION = 53;
  public static final int IZQUIERDA = 42;
  public static final int VIDEO = 37;
  public static final int ETIQUETAS = 9;
  public static final int CODIGO_COLOR = 52;
  public static final int MENU = 38;
  public static final int IDENTIFICADOR = 51;
  public static final int IGUAL = 15;
  public static final int CENTRAR = 41;
  public static final int TITULO = 25;
  public static final int PADRE = 27;
  public static final int ID = 18;
  public static final int NUEVA_PAGINA = 24;
  public static final int EOF = 0;
  public static final int BORRAR_COMPONENTE = 33;
  public static final int CLASE = 32;
  public static final int error = 1;
  public static final int COMILLA = 16;
  public static final int FECHA_MODIFICACION = 21;
  public static final int MAYOR_QUE = 14;
  public static final int URL = 54;
  public static final int ATRIBUTOS = 6;
  public static final int BORRAR_SITIO_WEB = 23;
  public static final int ATRIBUTO = 7;
  public static final int ACCION = 2;
  public static final int COLOR = 45;
  public static final int USUARIO_MODIFICACION = 22;
  public static final int FECHA_CREACION = 20;
  public static final int NUEVO_SITIO_WEB = 17;
  public static final int USUARIO_CREACION = 19;
  public static final int VALOR = 11;
  public static final int DERECHA = 43;
  public static final int IMAGEN = 36;
  public static final int ORIGEN = 46;
  public static final int PARRAFO = 35;
  public static final int MODIFICAR_COMPONENTE = 34;
  public static final int AGREGAR_COMPONENTE = 30;
  public static final int PARAMETRO = 5;
  public static final int ACCIONES = 3;
  public static final int SITIO = 26;
  public static final int MENOR_QUE = 13;
  public static final int TEXTO = 39;
  public static final int ETIQUETA = 10;
  public static final int ALTURA = 47;
  public static final int JUSTIFICAR = 44;
  public static final int MODIFICAR_PAGINA = 29;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ACCION",
  "ACCIONES",
  "PARAMETROS",
  "PARAMETRO",
  "ATRIBUTOS",
  "ATRIBUTO",
  "NOMBRE",
  "ETIQUETAS",
  "ETIQUETA",
  "VALOR",
  "DIAGONAL",
  "MENOR_QUE",
  "MAYOR_QUE",
  "IGUAL",
  "COMILLA",
  "NUEVO_SITIO_WEB",
  "ID",
  "USUARIO_CREACION",
  "FECHA_CREACION",
  "FECHA_MODIFICACION",
  "USUARIO_MODIFICACION",
  "BORRAR_SITIO_WEB",
  "NUEVA_PAGINA",
  "TITULO",
  "SITIO",
  "PADRE",
  "BORRAR_PAGINA",
  "MODIFICAR_PAGINA",
  "AGREGAR_COMPONENTE",
  "PAGINA",
  "CLASE",
  "BORRAR_COMPONENTE",
  "MODIFICAR_COMPONENTE",
  "PARRAFO",
  "IMAGEN",
  "VIDEO",
  "MENU",
  "TEXTO",
  "ALINEACION",
  "CENTRAR",
  "IZQUIERDA",
  "DERECHA",
  "JUSTIFICAR",
  "COLOR",
  "ORIGEN",
  "ALTURA",
  "ANCHO",
  "NUMERO",
  "FORMATO_FECHA",
  "IDENTIFICADOR",
  "CODIGO_COLOR",
  "ORACION",
  "URL",
  "IDENTIFICADOR_COMILLA"
  };
}

