/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend.gui;

import Run.Run;
import backend.analizadorParaTextoDeCliente.AnalizadorLexicoTextoCliente;
import backend.analizadorParaTextoDeCliente.parser;
import backend.elementos.Usuario;
import java.io.BufferedReader;
import java.io.StringReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.BadLocationException;

/**
 *
 * @author jesfrin
 */
public class ClienteFrame extends javax.swing.JFrame {

    private Usuario usuario;
    /**
     * Creates new form ClienteFrame
     */
    public ClienteFrame(Usuario usuario) {
        this.usuario=usuario;
        initComponents();
        this.setLocationRelativeTo(null);//Configurando su posicion en el centro

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        enviarTextoButton = new javax.swing.JButton();
        numeroDeColumnaLabel = new javax.swing.JLabel();
        numeroDeFilaLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoDeClienteTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        erroresTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        enviarTextoButton.setFont(new java.awt.Font("TlwgTypewriter", 0, 18)); // NOI18N
        enviarTextoButton.setText("Enviar");
        enviarTextoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarTextoButtonActionPerformed(evt);
            }
        });

        numeroDeColumnaLabel.setFont(new java.awt.Font("TlwgTypewriter", 0, 18)); // NOI18N
        numeroDeColumnaLabel.setText("#Columna");

        numeroDeFilaLabel.setFont(new java.awt.Font("TlwgTypewriter", 0, 18)); // NOI18N
        numeroDeFilaLabel.setText("#Linea");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enviarTextoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numeroDeColumnaLabel)
                    .addComponent(numeroDeFilaLabel))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(numeroDeFilaLabel)
                .addGap(30, 30, 30)
                .addComponent(numeroDeColumnaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(enviarTextoButton)
                .addGap(21, 21, 21))
        );

        textoDeClienteTextArea.setColumns(20);
        textoDeClienteTextArea.setRows(5);
        textoDeClienteTextArea.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                textoDeClienteTextAreaCaretUpdate(evt);
            }
        });
        jScrollPane1.setViewportView(textoDeClienteTextArea);

        erroresTextArea.setEditable(false);
        erroresTextArea.setColumns(20);
        erroresTextArea.setRows(5);
        jScrollPane2.setViewportView(erroresTextArea);

        jLabel1.setFont(new java.awt.Font("TlwgTypewriter", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("APLICACION CLIENTE");

        jLabel2.setFont(new java.awt.Font("TlwgTypewriter", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Errores ...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel1)
                .addContainerGap(430, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(jLabel2)
                    .addContainerGap(706, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(364, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(117, 117, 117)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enviarTextoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarTextoButtonActionPerformed
        this.erroresTextArea.setText("");
        analizarTexto();
    }//GEN-LAST:event_enviarTextoButtonActionPerformed

    private void textoDeClienteTextAreaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_textoDeClienteTextAreaCaretUpdate
                int pos = evt.getDot(); //mira los pasos del puntero
        try {
            int fila = textoDeClienteTextArea.getLineOfOffset(pos) + 1; //devuelve la fila
            int columna = pos - textoDeClienteTextArea.getLineStartOffset(fila - 1) + 1; //devuelve la columna
            this.numeroDeColumnaLabel.setText("#Columna:" + " " + columna + "");
            this.numeroDeFilaLabel.setText("#Linea:" + " " + fila);

        } catch (BadLocationException exc) {
        }
    }//GEN-LAST:event_textoDeClienteTextAreaCaretUpdate

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enviarTextoButton;
    private javax.swing.JTextArea erroresTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel numeroDeColumnaLabel;
    private javax.swing.JLabel numeroDeFilaLabel;
    private javax.swing.JTextArea textoDeClienteTextArea;
    // End of variables declaration//GEN-END:variables

    private void analizarTexto() {
        String instruccion = this.textoDeClienteTextArea.getText();
        if (instruccion.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese texto para continuar");
        } else {
            AnalizadorLexicoTextoCliente lexico = new AnalizadorLexicoTextoCliente(new BufferedReader(new StringReader(instruccion)));
            lexico.iniciarFrame(this);
            parser sintactico = new parser(lexico,this.usuario,this);
            try {
                sintactico.parse();
            } catch (Exception ex) {
                Logger.getLogger(Run.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    public void mostrarError(String tipo,int linea, int columna,String lexema){
        String texto;
        if(tipo.equalsIgnoreCase("lexico")){
            texto="Error LEXICO en linea:"+linea+" "+"Columna:"+columna+" "+"Lexema:"+lexema+"\n";
        }else if(tipo.equalsIgnoreCase("sintactico")){
            texto="Error SINTACTICO linea:"+linea+" "+"Columna:"+columna+" "+"Lexema:"+lexema+"\n";
        }else{
            texto="Error SINTACTICO VALOR REPETIDO linea:"+linea+" "+"Columna:"+columna+" "+"Lexema:"+lexema+"\n";
        }
        
        this.erroresTextArea.append(texto);
    }
}
