
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package backend.analizadorParaLogin;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAYOR_QUE = 7;
  public static final int USUARIO = 2;
  public static final int FORMATO_PASSWORD = 9;
  public static final int EOF = 0;
  public static final int MENOR_QUE = 6;
  public static final int DIAGONAL = 5;
  public static final int ID = 8;
  public static final int error = 1;
  public static final int NOMBRE = 3;
  public static final int PASSWORD = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "USUARIO",
  "NOMBRE",
  "PASSWORD",
  "DIAGONAL",
  "MENOR_QUE",
  "MAYOR_QUE",
  "ID",
  "FORMATO_PASSWORD"
  };
}

